<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="18" total="20" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Rohith test Suite" duration-ms="864762" started-at="2017-07-02T14:58:20Z" finished-at="2017-07-02T15:12:45Z">
    <groups>
      <group name="group2">
        <method signature="PracticeMethods.usingDropDown()[pri:1, instance:javapracticeone.PracticeMethods@196751b]" name="usingDropDown" class="javapracticeone.PracticeMethods"/>
        <method signature="PracticeMethods.printEvenNumber()[pri:3, instance:javapracticeone.PracticeMethods@196751b]" name="printEvenNumber" class="javapracticeone.PracticeMethods"/>
        <method signature="PracticeMethods.printLinks()[pri:7, instance:javapracticeone.PracticeMethods@196751b]" name="printLinks" class="javapracticeone.PracticeMethods"/>
        <method signature="PracticeMethods.printAllLinks()[pri:9, instance:javapracticeone.PracticeMethods@196751b]" name="printAllLinks" class="javapracticeone.PracticeMethods"/>
        <method signature="PracticeMethods.handlingAlerts()[pri:11, instance:javapracticeone.PracticeMethods@196751b]" name="handlingAlerts" class="javapracticeone.PracticeMethods"/>
        <method signature="PracticeMethods.handlingPrompts()[pri:13, instance:javapracticeone.PracticeMethods@196751b]" name="handlingPrompts" class="javapracticeone.PracticeMethods"/>
        <method signature="PracticeMethods.countFrames()[pri:15, instance:javapracticeone.PracticeMethods@196751b]" name="countFrames" class="javapracticeone.PracticeMethods"/>
        <method signature="PracticeMethods.readContent()[pri:17, instance:javapracticeone.PracticeMethods@196751b]" name="readContent" class="javapracticeone.PracticeMethods"/>
        <method signature="PracticeMethods.usingWrapperMethods()[pri:19, instance:javapracticeone.PracticeMethods@196751b]" name="usingWrapperMethods" class="javapracticeone.PracticeMethods"/>
      </group> <!-- group2 -->
      <group name="group1">
        <method signature="PracticeMethods.checkPrimeNumber()[pri:2, instance:javapracticeone.PracticeMethods@196751b]" name="checkPrimeNumber" class="javapracticeone.PracticeMethods"/>
        <method signature="PracticeMethods.usingLoops()[pri:4, instance:javapracticeone.PracticeMethods@196751b]" name="usingLoops" class="javapracticeone.PracticeMethods"/>
        <method signature="PracticeMethods.fibonacciSeries()[pri:5, instance:javapracticeone.PracticeMethods@196751b]" name="fibonacciSeries" class="javapracticeone.PracticeMethods"/>
        <method signature="PracticeMethods.useTwitterUsingObjectRepo()[pri:6, instance:javapracticeone.PracticeMethods@196751b]" name="useTwitterUsingObjectRepo" class="javapracticeone.PracticeMethods"/>
        <method signature="PracticeMethods.countDropdown()[pri:8, instance:javapracticeone.PracticeMethods@196751b]" name="countDropdown" class="javapracticeone.PracticeMethods"/>
        <method signature="PracticeMethods.useAllMethods()[pri:10, instance:javapracticeone.PracticeMethods@196751b]" name="useAllMethods" class="javapracticeone.PracticeMethods"/>
        <method signature="PracticeMethods.handlingFrame()[pri:12, instance:javapracticeone.PracticeMethods@196751b]" name="handlingFrame" class="javapracticeone.PracticeMethods"/>
        <method signature="PracticeMethods.handlingWindows()[pri:14, instance:javapracticeone.PracticeMethods@196751b]" name="handlingWindows" class="javapracticeone.PracticeMethods"/>
        <method signature="PracticeMethods.closeFrames()[pri:16, instance:javapracticeone.PracticeMethods@196751b]" name="closeFrames" class="javapracticeone.PracticeMethods"/>
        <method signature="PracticeMethods.starPattern()[pri:18, instance:javapracticeone.PracticeMethods@196751b]" name="starPattern" class="javapracticeone.PracticeMethods"/>
        <method signature="PracticeMethods.dataUsingDataProvider(java.lang.String, java.lang.String)[pri:20, instance:javapracticeone.PracticeMethods@196751b]" name="dataUsingDataProvider" class="javapracticeone.PracticeMethods"/>
      </group> <!-- group1 -->
    </groups>
    <test name="Rohith&#039;s test" duration-ms="864762" started-at="2017-07-02T14:58:20Z" finished-at="2017-07-02T15:12:45Z">
      <class name="javapracticeone.PracticeMethods">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="beforeSuite" is-config="true" duration-ms="34" started-at="2017-07-02T20:28:20Z" finished-at="2017-07-02T20:28:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="beforeTest" is-config="true" duration-ms="1" started-at="2017-07-02T20:28:20Z" finished-at="2017-07-02T20:28:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="beforeClass" is-config="true" duration-ms="0" started-at="2017-07-02T20:28:20Z" finished-at="2017-07-02T20:28:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="usingDropDown()[pri:1, instance:javapracticeone.PracticeMethods@196751b]" name="usingDropDown" duration-ms="150712" started-at="2017-07-02T20:28:20Z" description="Interacting with drop down" finished-at="2017-07-02T20:30:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- usingDropDown -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterMethod" is-config="true" duration-ms="1" started-at="2017-07-02T20:30:51Z" finished-at="2017-07-02T20:30:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="checkPrimeNumber()[pri:2, instance:javapracticeone.PracticeMethods@196751b]" name="checkPrimeNumber" duration-ms="21" started-at="2017-07-02T20:30:51Z" description="Java program to find out whether a number is prime or not" depends-on-methods="javapracticeone.PracticeMethods.usingDropDown" finished-at="2017-07-02T20:30:51Z">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:505)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1441)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:201)
	at javapracticeone.PracticeMethods.checkPrimeNumber(PracticeMethods.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:496)
	... 16 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkPrimeNumber -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-07-02T20:30:51Z" finished-at="2017-07-02T20:30:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="printEvenNumber()[pri:3, instance:javapracticeone.PracticeMethods@196751b]" name="printEvenNumber" duration-ms="20" started-at="2017-07-02T20:30:51Z" description="To print the even numbers between 100 and 200" depends-on-methods="javapracticeone.PracticeMethods.checkPrimeNumber" finished-at="2017-07-02T20:30:51Z">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:505)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1441)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:201)
	at javapracticeone.PracticeMethods.printEvenNumber(PracticeMethods.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:496)
	... 16 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- printEvenNumber -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-07-02T20:30:51Z" finished-at="2017-07-02T20:30:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="usingLoops()[pri:4, instance:javapracticeone.PracticeMethods@196751b]" name="usingLoops" duration-ms="6074" started-at="2017-07-02T20:30:51Z" description="Using various types of loops" depends-on-methods="javapracticeone.PracticeMethods.printEvenNumber" finished-at="2017-07-02T20:30:57Z">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:505)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1441)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:201)
	at javapracticeone.PracticeMethods.usingLoops(PracticeMethods.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:496)
	... 16 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- usingLoops -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterMethod" is-config="true" duration-ms="1" started-at="2017-07-02T20:30:57Z" finished-at="2017-07-02T20:30:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="fibonacciSeries()[pri:5, instance:javapracticeone.PracticeMethods@196751b]" name="fibonacciSeries" duration-ms="25" started-at="2017-07-02T20:30:57Z" description="Fibonacci series" depends-on-methods="javapracticeone.PracticeMethods.usingLoops" finished-at="2017-07-02T20:30:57Z">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:505)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1441)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:201)
	at javapracticeone.PracticeMethods.fibonacciSeries(PracticeMethods.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:496)
	... 16 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fibonacciSeries -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-07-02T20:30:57Z" finished-at="2017-07-02T20:30:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="useTwitterUsingObjectRepo()[pri:6, instance:javapracticeone.PracticeMethods@196751b]" name="useTwitterUsingObjectRepo" duration-ms="105504" started-at="2017-07-02T20:30:57Z" description="Access twitter using object repository" depends-on-methods="javapracticeone.PracticeMethods.fibonacciSeries" finished-at="2017-07-02T20:32:42Z">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:505)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1441)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:201)
	at javapracticeone.PracticeMethods.useTwitterUsingObjectRepo(PracticeMethods.java:317)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:496)
	... 15 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- useTwitterUsingObjectRepo -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterMethod" is-config="true" duration-ms="1" started-at="2017-07-02T20:32:42Z" finished-at="2017-07-02T20:32:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="printLinks()[pri:7, instance:javapracticeone.PracticeMethods@196751b]" name="printLinks" duration-ms="122093" started-at="2017-07-02T20:32:42Z" description="Printing the links with your name" depends-on-methods="javapracticeone.PracticeMethods.useTwitterUsingObjectRepo" finished-at="2017-07-02T20:34:45Z">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:505)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1441)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:201)
	at javapracticeone.PracticeMethods.printLinks(PracticeMethods.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:496)
	... 16 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- printLinks -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-07-02T20:34:45Z" finished-at="2017-07-02T20:34:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="countDropdown()[pri:8, instance:javapracticeone.PracticeMethods@196751b]" name="countDropdown" duration-ms="33330" started-at="2017-07-02T20:34:45Z" description="counting the number of dropdown entries in the page" depends-on-methods="javapracticeone.PracticeMethods.printLinks" finished-at="2017-07-02T20:35:18Z">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:505)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1441)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:201)
	at javapracticeone.PracticeMethods.countDropdown(PracticeMethods.java:411)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:496)
	... 16 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- countDropdown -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterMethod" is-config="true" duration-ms="1" started-at="2017-07-02T20:35:18Z" finished-at="2017-07-02T20:35:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="printAllLinks()[pri:9, instance:javapracticeone.PracticeMethods@196751b]" name="printAllLinks" duration-ms="22918" started-at="2017-07-02T20:35:18Z" description="print all the links in google.com" depends-on-methods="javapracticeone.PracticeMethods.countDropdown" finished-at="2017-07-02T20:35:41Z">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:505)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1441)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:201)
	at javapracticeone.PracticeMethods.printAllLinks(PracticeMethods.java:449)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:496)
	... 16 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- printAllLinks -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-07-02T20:35:41Z" finished-at="2017-07-02T20:35:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="useAllMethods()[pri:10, instance:javapracticeone.PracticeMethods@196751b]" name="useAllMethods" duration-ms="45943" started-at="2017-07-02T20:35:41Z" description="using all methods" depends-on-methods="javapracticeone.PracticeMethods.printAllLinks" finished-at="2017-07-02T20:36:27Z">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:505)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1441)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:201)
	at javapracticeone.PracticeMethods.useAllMethods(PracticeMethods.java:496)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:496)
	... 16 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- useAllMethods -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-07-02T20:36:27Z" finished-at="2017-07-02T20:36:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="handlingAlerts()[pri:11, instance:javapracticeone.PracticeMethods@196751b]" name="handlingAlerts" duration-ms="34163" started-at="2017-07-02T20:36:27Z" description="Handling alerts" depends-on-methods="javapracticeone.PracticeMethods.useAllMethods" finished-at="2017-07-02T20:37:01Z">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:505)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1441)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:201)
	at javapracticeone.PracticeMethods.handlingAlerts(PracticeMethods.java:537)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:496)
	... 16 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- handlingAlerts -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-07-02T20:37:01Z" finished-at="2017-07-02T20:37:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="handlingFrame()[pri:12, instance:javapracticeone.PracticeMethods@196751b]" name="handlingFrame" duration-ms="36200" started-at="2017-07-02T20:37:01Z" description="handling frames" depends-on-methods="javapracticeone.PracticeMethods.handlingAlerts" finished-at="2017-07-02T20:37:38Z">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:505)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1441)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:201)
	at javapracticeone.PracticeMethods.handlingFrame(PracticeMethods.java:588)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:496)
	... 16 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- handlingFrame -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-07-02T20:37:38Z" finished-at="2017-07-02T20:37:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="handlingPrompts()[pri:13, instance:javapracticeone.PracticeMethods@196751b]" name="handlingPrompts" duration-ms="34248" started-at="2017-07-02T20:37:38Z" description="Handling prompts" depends-on-methods="javapracticeone.PracticeMethods.handlingFrame" finished-at="2017-07-02T20:38:12Z">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:505)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1441)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:201)
	at javapracticeone.PracticeMethods.handlingPrompts(PracticeMethods.java:658)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:496)
	... 16 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- handlingPrompts -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-07-02T20:38:12Z" finished-at="2017-07-02T20:38:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="handlingWindows()[pri:14, instance:javapracticeone.PracticeMethods@196751b]" name="handlingWindows" duration-ms="26226" started-at="2017-07-02T20:38:12Z" description="Handling windows" depends-on-methods="javapracticeone.PracticeMethods.handlingPrompts" finished-at="2017-07-02T20:38:38Z">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:505)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1441)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:201)
	at javapracticeone.PracticeMethods.handlingWindows(PracticeMethods.java:741)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:496)
	... 16 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- handlingWindows -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-07-02T20:38:38Z" finished-at="2017-07-02T20:38:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="countFrames()[pri:15, instance:javapracticeone.PracticeMethods@196751b]" name="countFrames" duration-ms="51232" started-at="2017-07-02T20:38:38Z" description="Counting the number of frames in a webpage" depends-on-methods="javapracticeone.PracticeMethods.handlingWindows" finished-at="2017-07-02T20:39:29Z">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:505)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1441)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:201)
	at javapracticeone.PracticeMethods.countFrames(PracticeMethods.java:787)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:496)
	... 16 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- countFrames -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-07-02T20:39:29Z" finished-at="2017-07-02T20:39:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="closeFrames()[pri:16, instance:javapracticeone.PracticeMethods@196751b]" name="closeFrames" duration-ms="32856" started-at="2017-07-02T20:39:29Z" description="closing the frames in the web page" depends-on-methods="javapracticeone.PracticeMethods.countFrames" finished-at="2017-07-02T20:40:02Z">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:505)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1441)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:201)
	at javapracticeone.PracticeMethods.closeFrames(PracticeMethods.java:841)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:496)
	... 16 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeFrames -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-07-02T20:40:02Z" finished-at="2017-07-02T20:40:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="readContent()[pri:17, instance:javapracticeone.PracticeMethods@196751b]" name="readContent" duration-ms="23001" started-at="2017-07-02T20:40:02Z" description="read the content within a frame" depends-on-methods="javapracticeone.PracticeMethods.closeFrames" finished-at="2017-07-02T20:40:25Z">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:505)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1441)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:201)
	at javapracticeone.PracticeMethods.readContent(PracticeMethods.java:883)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:496)
	... 16 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readContent -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterMethod" is-config="true" duration-ms="1" started-at="2017-07-02T20:40:25Z" finished-at="2017-07-02T20:40:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="starPattern()[pri:18, instance:javapracticeone.PracticeMethods@196751b]" name="starPattern" duration-ms="7" started-at="2017-07-02T20:40:25Z" description="print stars" depends-on-methods="javapracticeone.PracticeMethods.readContent" finished-at="2017-07-02T20:40:25Z">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:505)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1441)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:201)
	at javapracticeone.PracticeMethods.starPattern(PracticeMethods.java:908)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:496)
	... 16 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- starPattern -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-07-02T20:40:25Z" finished-at="2017-07-02T20:40:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="usingWrapperMethods()[pri:19, instance:javapracticeone.PracticeMethods@196751b]" name="usingWrapperMethods" duration-ms="139029" started-at="2017-07-02T20:40:25Z" description="using wrapper methods" depends-on-methods="javapracticeone.PracticeMethods.starPattern" finished-at="2017-07-02T20:42:44Z">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:505)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1441)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:201)
	at javapracticeone.PracticeMethods.usingWrapperMethods(PracticeMethods.java:941)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@1fe4a43
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:496)
	... 16 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- usingWrapperMethods -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-07-02T20:42:44Z" finished-at="2017-07-02T20:42:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method name="dataUsingDataProvider" signature="dataUsingDataProvider(java.lang.String, java.lang.String)[pri:20, instance:javapracticeone.PracticeMethods@196751b]" status="SKIP" duration-ms="0" finished-at="2017-07-02T20:42:44Z" started-at="2017-07-02T20:42:44Z" depends-on-methods="javapracticeone.PracticeMethods.usingWrapperMethods" data-provider="useData" description="using data provider">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void javapracticeone.PracticeMethods.dataUsingDataProvider(java.lang.String,java.lang.String) throws java.io.IOException requires a @DataProvider named : useData]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void javapracticeone.PracticeMethods.dataUsingDataProvider(java.lang.String,java.lang.String) throws java.io.IOException requires a @DataProvider named : useData
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:262)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:418)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1269)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataUsingDataProvider -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterClass" is-config="true" duration-ms="0" started-at="2017-07-02T20:42:44Z" finished-at="2017-07-02T20:42:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterTest" is-config="true" duration-ms="1" started-at="2017-07-02T20:42:45Z" finished-at="2017-07-02T20:42:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:javapracticeone.PracticeMethods@196751b]" name="afterSuite" is-config="true" duration-ms="121" started-at="2017-07-02T20:42:45Z" finished-at="2017-07-02T20:42:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- javapracticeone.PracticeMethods -->
    </test> <!-- Rohith's test -->
  </suite> <!-- Rohith test Suite -->
</testng-results>
